name: Build and push Docker images

on:
    release:
        branches: [master]
        tags: ['*']

jobs:
    build:
        name: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build and push stable Docker image
              uses: docker/build-push-action@v1.1.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  repository: nessmcfr/ts-discordjs
                  dockerfile: Dockerfile
                  # tag with the git commit SHA
                  tag_with_sha: true
                  tags: latest
                  # push the image only if the event that kicked off the workflow was a push of a git tah
                  push: ${{ startsWith(github.ref, 'refs/tags/') }}
